name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd app
        docker build . --tag cicdapp
    
    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
     # Build the Docker image
     # Tag the Docker image 
    - name: Build Docker image and push it to Docker Hub
      run: | 
        cd app
        docker tag cicdapp ${{ secrets.DOCKER_USERNAME }}/cicdapp:latest
        docker build -t ${{ secrets.DOCKER_USERNAME }}/cicdapp:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/cicdapp:latest

